### ISSUE TITLE
P5 Kata: House

### ISSUE THREAD

**Issue by codingbootcampseu** [Lulezimukaj/bootcamp-schedule#64]
- Create a house with p5
- The basic house should look like [this](https://editor.p5js.org/CodingBootcampsEu/full/OxAoEpuqj)
- A minimal example solution can be found [here](https://editor.p5js.org/CodingBootcampsEu/sketches/OxAoEpuqj)

**Hints**

You will need the `triangle()` function to draw the house - so here is the [triangle() reference](https://p5js.org/reference/#/p5/triangle)

**Bonus**

- Create windows and doors as well
- Use distinct colors for the roof and the rest of the house

**Comment by Lulezimukaj** [comment]
let canvasBase = 400;

function setup() {
  createCanvas(canvasBase, canvasBase)
  background ("grey")
  
}

function draw() {
  fill ("red")
 triangle (200,50, 70, 200, 330, 200)
  fill ("green")
  rect (70, 200, 260, 150)
  fill ("white")
  rect (180, 290, 40, 60)
  rect (110, 220, 40)
  rect (250, 220, 40)
}
